### ISSUE TITLE
Type confusion between `Int` and `Float` in the move resolver

### ISSUE THREAD

**Issue by Amanieu** [bytecodealliance/regalloc2#79]
This only happens when both `Int` and `Float` classes have the same spillslot size.

The root of the problem is that a single spillslot can be used (separately) to hold values of either class. This is because spill slot allocation only looks at `slots_by_size` and ignores the register class of the spillset. The class of the `SpillSlot` seems to be whichever spillset first allocates this spillslot ([source](https://github.com/bytecodealliance/regalloc2/blob/aeef47a06b88be80a37d160bf21632b7dc0a95a4/src/ion/spill.rs#L168)).

This seems to be intentional since the move resolution code specifically ignores the register class on spillslots ([1](https://github.com/bytecodealliance/regalloc2/blob/aeef47a06b88be80a37d160bf21632b7dc0a95a4/src/ion/moves.rs#L67) [2](https://github.com/bytecodealliance/regalloc2/blob/aeef47a06b88be80a37d160bf21632b7dc0a95a4/src/ion/moves.rs#L1113) [3](https://github.com/bytecodealliance/regalloc2/blob/main/src/ion/moves.rs#L974)).

However this causes problems when constructing the move lists because the register class is obtained from [`m.from_alloc.class()`](https://github.com/bytecodealliance/regalloc2/blob/aeef47a06b88be80a37d160bf21632b7dc0a95a4/src/ion/moves.rs#L980) which may be incorrect if `from_alloc` is a spillslot (i.e. it won't match the class of the other registers in the move list).

I can see 2 ways we might fix this:
1. Require that a spillslot only be used with a single register class. This may end up increasing stack usage.
2. Completely remove the register class from `SpillSlot`. But then the move resolver needs some way to know which scratch register to use for resolving stack-to-stack moves.

**Comment by Amanieu** [comment]
I have a test case that reproduces this but it's a huge function (16044 vregs, 2008 blocks) that generates a 2GB log file with `trace-log`.

**Comment by Amanieu** [comment]
At the moment I'm using a workaround by checking the register class in `spillslot_can_fit_spillset` but I'm not sure what the best long-term solution is here.

**Comment by cfallin** [comment]
Interesting -- thank you for finding this!

(To delimit the scope for any other observers: not reachable from Cranelift, because the vanilla ABI code requires 16-byte spillslots for all float regs and 8-byte for GPRs. Still very much a real problem in the case @Amanieu describes.)

I'm actually leaning toward your second option here:

> 2. Completely remove the register class from SpillSlot. But then the move resolver needs some way to know which scratch register to use for resolving stack-to-stack moves.

with the additional thought that we don't actually need to match the regclass that is used in order to generate instructions for a stack-to-stack move; rather we need some reverse-mapping from spillslot size to register class. This is because, in the case that both `Int` and `Float` take one spillslot, it's actually *fine* to use (for example) a GPR to do a stack-to-stack move of a float value, no? All that matters is that we move the bits. So in a Cranelift-like embedder, we have `fn spillslot_size_to_class(slots: usize) -> RegClass { match slots { 1 => RegClass::Int, 2 => RegClass::Float, _ => panic!() } }`; and in your case you just need `1 => RegClass::Int`.
